### ISSUE TITLE
Problem on PTT

### ISSUE THREAD

**Issue by nyj1911** [Pingu-Io/better-salty-nui#1]
when switch to Teamspeak PTT  then in-game ts3 status is keep pop out and not connected , if setting to voice auto-detect everything works fine... hope can solve this problem

**Comment by Pingu-Io** [comment]
I've just released the v1.1, it should fix the problem

**Comment by nyj1911** [comment]
thank you for the respond, problem solved on PTT and can I know each time i logging to server the microphone is not checking and after manually turn off / on the mic then only back to normal , is that normal or bugged?

**Comment by Pingu-Io** [comment]
It's "normal", I can't fix it.

**Comment by nyj1911** [comment]
ok no problem , thank you so much
